---
- name: find
  hosts: linoop
  tasks:
  - name: Find /var/log files equal or greater than 10 megabytes ending with .old 
    find:
       paths: /var/log
       patterns: '*.old,*.log.gz'
       size: 10m
