---
- name: installing packages
  hosts: 192.168.0.191
  tasks:
    - name: installing multiple rpms
      yum:
        name: "{{ item }}"
        state: present
      with_items:
        - vsftpd
        - dhcp
        - telnet
        - tree
        - httpd
