---
- name: create repository
  hosts: cls
  become: root
  become_user: root
  vars:
   rpm1: httpd
   rpm2: createrepo
   svc1: httpd
   tasks:
   - name: installing packages
     yum:
      name:
       - "{{ rpm1 }}"
       - "{{ rpm2 }}"
      state: present
   - name: start and enable service
     service:
      name: "{{ svc1 }}"
      state: started
      enabled: yes
   - name: make directory
     file:
      path: /var/www/html/syedrepodir
      state: directory
      mode: '0755'
   - name: copy Packages
     shell: cp -avr /media/CentOS_6.10_Final/Packages/* /var/www/html/syedrepodir
   - name: make metadata of syedrepodir
     shell: createrepo /var/www/html/syedrepodir
   - name: STOPPING IPTALBES and
     service:
      name: iptables
      state: stopped
   - name: make file
     file:
      path: /etc/yum.repos.d/syed.repo
      state: touch
   - name: copy a repo file
     blockinfile:
      path: /etc/yum.repos.d/syed.repo
      block: |
       [syedrepo]
       name=syedlocalrepo
       baseurl=http://192.168.0.191/syedrepodir
       enabled=1
       gpgcheck=0
   - name: clean repo
     shell: yum clean all
