---
- name: nfs client
  hosts: 192.168.0.191
  become: root
  tasks:
  - name: disable SElinux
    selinux:
      policy: targeted
      state: disabled
  - name: stopping and disablling iptables
    service: 
      name: iptables
      state: stopped
      enabled: no
  - name: install nfs-utils
    yum:
      name: nfs-utils
      state: present 
  - name: starting and enabling nfs 
    service:
      name: nfs
      state: started
      enabled: yes
  - name: creating nfs share directory
    file:
      path: /data1
      state: directory
  - name: creating share
    lineinfile:
      path: /etc/exports
      line: '/data1 *(rw,no_root_squash,sync)'
  - name: exporting and initial share
    shell: "exportfs -avr; showmount -e 192.168.0.191"



